INSERT INTO "public"."agents"(name, username, password, description, experience, agency_id, banner_name, banner_link, profile_name, profile_link, email, phone_number, created_at, created_by, updated_at, updated_by, deleted, deleted_at, deleted_by) VALUES
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0'),
('Ole', 'olealex8', 'password', 'testing_desc', 'testing_exp', '1', 'testing_banner', 'https://picsum.photos/200', 'Ole Alexander', 'testing_profile_link', 'olealex8@gmail.com', '081318101175', now(), '1', now(), '1', '0', now(), '0');


INSERT INTO "public"."review"(agent_id, property_id, user_id, agency_id, category, description, rating, verify_admin_id, created_at, created_by, updated_at, updated_by, deleted, deleted_at, deleted_by) VALUES
(1, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(2, 1, 1, 1, 'testing_category', 'testing_desc', 4, 1, now(), '1', now(), '1', '0', now(), '0'),
(3, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(3, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(5, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(1, 1, 1, 1, 'testing_category', 'testing_desc', 5, 1, now(), '1', now(), '1', '0', now(), '0'),
(2, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(10, 1, 1, 1, 'testing_category', 'testing_desc', 5, 1, now(), '1', now(), '1', '0', now(), '0'),
(10, 1, 1, 1, 'testing_category', 'testing_desc', 5, 1, now(), '1', now(), '1', '0', now(), '0'),
(5, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(5, 1, 1, 1, 'testing_category', 'testing_desc', 4, 1, now(), '1', now(), '1', '0', now(), '0'),
(3, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(1, 1, 1, 1, 'testing_category', 'testing_desc', 1, 1, now(), '1', now(), '1', '0', now(), '0'),
(2, 1, 1, 1, 'testing_category', 'testing_desc', 1, 1, now(), '1', now(), '1', '0', now(), '0'),
(3, 1, 1, 1, 'testing_category', 'testing_desc', 4, 1, now(), '1', now(), '1', '0', now(), '0'),
(4, 1, 1, 1, 'testing_category', 'testing_desc', 2, 1, now(), '1', now(), '1', '0', now(), '0'),
(4, 1, 1, 1, 'testing_category', 'testing_desc', 4, 1, now(), '1', now(), '1', '0', now(), '0'),
(6, 1, 1, 1, 'testing_category', 'testing_desc', 1, 1, now(), '1', now(), '1', '0', now(), '0'),
(7, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(7, 1, 1, 1, 'testing_category', 'testing_desc', 5, 1, now(), '1', now(), '1', '0', now(), '0'),
(8, 1, 1, 1, 'testing_category', 'testing_desc', 5, 1, now(), '1', now(), '1', '0', now(), '0'),
(8, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(9, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(9, 1, 1, 1, 'testing_category', 'testing_desc', 3, 1, now(), '1', now(), '1', '0', now(), '0'),
(6, 1, 1, 1, 'testing_category', 'testing_desc', 4, 1, now(), '1', now(), '1', '0', now(), '0');